version: '3.8'

services:
  # PostgreSQL 개발용 DB
  postgres:
    image: postgres:15-alpine
    container_name: playground_dev_postgres
    environment:
      POSTGRES_DB: playground
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./playground/be/src/database/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - playground_dev
    restart: unless-stopped


volumes:
  postgres_dev_data:

networks:
  playground_dev:
    driver: bridge